version: '3.8'

services:
  oracle_db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: rohit
      APP_USER: rohit  
      APP_USER_PASSWORD: rohit
      ORACLE_DATABASE: XEPDB1
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/rohit@//localhost:1521/XEPDB1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  backend:
    build:
      context: .
      dockerfile: /backend/Dockerfile
    container_name: spring_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@192.168.1.103:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: rohit
    depends_on:
      oracle_db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: /my-app/Dockerfile
    container_name: react_frontend
    ports:
      - "4173:4173"
    networks:
      - app-network

volumes:
  oracle-data:
    driver: local

networks:
  app-network:
    driver: bridge
